/**
 * promptManifestLib.ts
 *
 * Shared utilities for the prompt-manifest check and update scripts.
 * No executable top-level code — safe to import from either script.
 */

import { createHash } from "crypto";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export const EXPLORE_FILE = resolve(
  __dirname,
  "../../../artifacts/api-server/src/routes/explore/index.ts",
);
export const MANIFEST_FILE = resolve(__dirname, "../../prompt-manifest.json");

export interface ManifestEntry {
  sectionHash: string;
  registered: string;
}

export interface Manifest {
  description: string;
  entries: Record<string, ManifestEntry>;
}

export const MANIFEST_DESCRIPTION =
  "Auto-generated by scripts/src/updatePromptManifest.ts — do not edit by hand. " +
  "Existing entries are immutable: bump the cache-key version before changing a prompt.";

export function hashText(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

/**
 * Split the source file into sections, one per router endpoint.
 * Returns a map of { routeKey → sectionText } where routeKey is:
 *   "<route-slug>:<version-token>"  e.g. "place-detail:v1", "place-timeline:v2"
 *
 * Only includes sections that contain an LLM cache-key version token.
 */
export function extractRouteSections(source: string): Map<string, string> {
  const result = new Map<string, string>();

  // Split on router.post / router.get boundaries (keep the delimiter)
  const sections = source.split(/(?=router\.(?:post|get)\s*\()/);

  for (const section of sections) {
    // Extract the route path slug (e.g. "/explore/place-detail" → "place-detail")
    const pathMatch = section.match(
      /router\.(?:post|get)\s*\(\s*["'`]\/explore\/([^"'`]+)["'`]/,
    );
    if (!pathMatch) continue;
    const slug = pathMatch[1];

    // Find all version tokens in this section.
    const versionTokens = new Set<string>();
    // Literal prefix form: "detail:v1:", "timeline:v2:", etc.
    for (const m of section.matchAll(/\b[a-z][a-z0-9-]*:(v\d+):/g)) {
      versionTokens.add(m[1]);
    }
    // Dynamic-prefix form: `${modeKey}:v1:`
    for (const m of section.matchAll(/\$\{[^}]+\}:(v\d+):/g)) {
      versionTokens.add(m[1]);
    }

    if (versionTokens.size === 0) continue;

    // Use the highest version token present (covers rare multi-version sections)
    const version = [...versionTokens].sort().at(-1)!;
    const routeKey = `${slug}:${version}`;

    result.set(routeKey, section);
  }

  return result;
}

/**
 * Parse the manifest file, handling migration from the old flat-hash format.
 * Returns a fresh empty manifest if the file is missing or uses the old format.
 */
export function parseManifest(raw: string): Manifest {
  const parsed = JSON.parse(raw) as Record<string, unknown>;
  if (!parsed.entries || typeof parsed.entries !== "object") {
    // Old format (pre-per-endpoint): discard and start fresh.
    return { description: MANIFEST_DESCRIPTION, entries: {} };
  }
  return parsed as unknown as Manifest;
}
