/**
 * promptManifestLib.ts
 *
 * Shared utilities for the prompt-manifest check and update scripts.
 * No executable top-level code — safe to import from either script.
 *
 * ## What gets protected, and at what granularity
 *
 * The guard scans every TypeScript file under SCAN_ROOT. For a file with no
 * `router.post(...)` / `router.get(...)` calls, the whole file is one
 * "module" entry (unchanged from the original whole-file design — e.g.
 * cacheVersions.ts).
 *
 * For a file WITH route boundaries (e.g. routes/explore/index.ts), the file
 * is split at each `router.post(`/`router.get(` boundary:
 *   - Everything before the first route boundary is a "module" entry (keyed
 *     by file path alone) — this protects shared, non-route-scoped cache
 *     keys such as an in-memory Wikipedia-summary lookup that sits above all
 *     the route handlers.
 *   - Each route's own section (from its `router.*(` call to the next route
 *     boundary, or EOF) becomes its own "route" entry, keyed
 *     `<filePath>::<route-slug>`. This means editing route A's handler can
 *     never force route B's cache-key version to bump.
 *
 * Within a route section, a route may OPT IN to explicit prompt regions by
 * wrapping the exact lines that affect model behavior — the cache-key
 * definition and the prompt/LLM-call construction — in matched
 *   // @prompt-region <route-slug>
 *   ...
 *   // @end-prompt-region [<route-slug>]
 * marker comments. When present, ONLY the text inside those marked spans is
 * hashed — logging, control flow, and other non-prompt code in the same
 * route handler can change freely without requiring a version bump. A route
 * with no markers falls back to hashing its entire section (the
 * conservative default), so unmarked routes remain exactly as strictly
 * protected as before this change.
 *
 * A route's own cache-key version token(s) must appear INSIDE its marked
 * regions if it has any — a version token found outside all of a marked
 * route's regions is treated as a scan error (see scanFileContent), because
 * a version bump could otherwise happen without ever touching the material
 * the guard actually hashes.
 */

import { createHash } from "crypto";
import { readdirSync, readFileSync, statSync } from "fs";
import { resolve, dirname, relative, sep } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export const REPO_ROOT = resolve(__dirname, "../../..");

/**
 * Root directory scanned for files that may contain LLM cache-key version
 * tokens. Anything matching SCAN_FILE_PATTERN below this directory is
 * inspected.
 */
export const SCAN_ROOT = resolve(REPO_ROOT, "artifacts/api-server/src");

/** File-name pattern (matched against the basename) for files to inspect. */
export const SCAN_FILE_PATTERN = /\.ts$/;

/** Directory names skipped during the scan. */
export const SCAN_IGNORED_DIRS = new Set([
  "node_modules",
  "dist",
  "build",
  ".turbo",
]);

export const MANIFEST_FILE = resolve(__dirname, "../../prompt-manifest.json");

export const SCHEMA_VERSION = 2 as const;

export type EntryKind = "module" | "route";
export type ExtractionMode =
  | "whole-file" // module entry, file has no route boundaries at all
  | "module-prefix" // module entry, file DOES have routes; this is the prefix before the first one
  | "marked" // route entry, route opted into @prompt-region markers
  | "section-fallback"; // route entry, no markers — whole route section hashed

export interface ManifestEntry {
  kind: EntryKind;
  extraction: ExtractionMode;
  sectionHash: string;
  versions: string[];
  registered: string;
}

export interface Manifest {
  description: string;
  schemaVersion: 2;
  entries: Record<string, ManifestEntry>;
}

export const MANIFEST_DESCRIPTION =
  "Auto-generated by scripts/src/updatePromptManifest.ts — do not edit by hand. " +
  "One entry per file (no route boundaries) or per route (files with " +
  "router.post/get calls). Routes may opt into explicit @prompt-region " +
  "markers to hash only their model-behavior-affecting lines; unmarked " +
  "routes conservatively hash their entire section. " +
  "Existing hashes are immutable: bump a cache-key version before changing " +
  "protected content.";

export function hashText(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

/**
 * Canonical, boundary-explicit hash for an ordered list of text spans.
 * Length-prefixes every span (rather than plain concatenation) so that two
 * different ways of splitting adjacent content can never collide — e.g.
 * spans ["ab", "c"] and ["a", "bc"] must never hash the same.
 */
export function hashSpans(spans: string[]): string {
  const encoded = spans.map((s) => `${s.length}:${s}`).join("\u0000");
  return hashText(`${spans.length}\u0000${encoded}`);
}

function toPosix(p: string): string {
  return sep === "/" ? p : p.split(sep).join("/");
}

function walk(dir: string, out: string[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const name of entries) {
    if (SCAN_IGNORED_DIRS.has(name)) continue;
    const full = resolve(dir, name);
    let s;
    try {
      s = statSync(full);
    } catch {
      continue;
    }
    if (s.isDirectory()) {
      walk(full, out);
    } else if (s.isFile() && SCAN_FILE_PATTERN.test(name)) {
      out.push(full);
    }
  }
}

const VERSION_TOKEN_RE = /\b[a-z][a-z0-9-]*:(v\d+):/g;
const VERSION_TOKEN_DYNAMIC_RE = /\$\{[^}]+\}:(v\d+):/g;

export interface VersionTokenMatch {
  version: string;
  /** Offset of the match within the text that was scanned. */
  index: number;
}

/** Find every LLM cache-key version token in `text`, with its offset. */
export function findVersionTokens(text: string): VersionTokenMatch[] {
  const out: VersionTokenMatch[] = [];
  for (const m of text.matchAll(VERSION_TOKEN_RE)) {
    out.push({ version: m[1]!, index: m.index! });
  }
  for (const m of text.matchAll(VERSION_TOKEN_DYNAMIC_RE)) {
    out.push({ version: m[1]!, index: m.index! });
  }
  return out;
}

function sortedUniqueVersions(tokens: VersionTokenMatch[]): string[] {
  return [...new Set(tokens.map((t) => t.version))].sort();
}

interface RouteBoundary {
  start: number;
  /** Last path segment of the route, or null if the path couldn't be parsed. */
  slug: string | null;
}

const ROUTE_CALL_RE = /router\.(?:post|get)\s*\(/g;
const ROUTE_PATH_RE = /router\.(?:post|get)\s*\(\s*["'`]([^"'`]+)["'`]/;

function findRouteBoundaries(source: string): RouteBoundary[] {
  const boundaries: RouteBoundary[] = [];
  for (const m of source.matchAll(ROUTE_CALL_RE)) {
    const start = m.index!;
    const tail = source.slice(start, start + 400);
    const pathMatch = tail.match(ROUTE_PATH_RE);
    let slug: string | null = null;
    if (pathMatch) {
      const segments = pathMatch[1]!.split("/").filter(Boolean);
      slug = segments.length > 0 ? segments[segments.length - 1]! : null;
    }
    boundaries.push({ start, slug });
  }
  return boundaries;
}

export interface PromptRegionSpan {
  /** Offsets are absolute within the whole file. */
  start: number;
  end: number;
  text: string;
}

const BEGIN_RE = /^[ \t]*\/\/[ \t]*@prompt-region[ \t]+([a-z0-9-]+)[ \t]*$/;
const END_RE =
  /^[ \t]*\/\/[ \t]*@end-prompt-region(?:[ \t]+([a-z0-9-]+))?[ \t]*$/;
const LOOSE_BEGIN_RE = /@prompt-region\b/;
const LOOSE_END_RE = /@end-prompt-region\b/;

/**
 * Parse `// @prompt-region <slug>` / `// @end-prompt-region [<slug>]`
 * marker pairs out of a single route's section text. Returns the ordered
 * list of marked spans (absolute file offsets) plus any structural errors:
 * unmatched, nested, mismatched, empty, or wrong-route markers, and any
 * comment that looks like a marker but doesn't match the strict syntax.
 * Multiple ordered pairs for the same route slug are expected and supported.
 */
export function extractPromptRegions(
  routeText: string,
  routeSlug: string,
  routeOffsetInFile: number,
  filePath: string,
): { spans: PromptRegionSpan[]; errors: string[] } {
  const lines = routeText.split("\n");
  const spans: PromptRegionSpan[] = [];
  const errors: string[] = [];
  let open: {
    slug: string;
    startLine: number;
    startOffset: number;
  } | null = null;
  let offset = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    const beginMatch = line.match(BEGIN_RE);
    const endMatch = line.match(END_RE);

    if (beginMatch) {
      if (open) {
        errors.push(
          `${filePath}: nested @prompt-region at route "${routeSlug}" line ~${i} — region "${beginMatch[1]}" opened while "${open.slug}" is still open`,
        );
      } else {
        const declaredSlug = beginMatch[1]!;
        if (declaredSlug !== routeSlug) {
          errors.push(
            `${filePath}: @prompt-region "${declaredSlug}" found inside route "${routeSlug}"'s section (wrong-route marker) at line ~${i}`,
          );
        }
        open = {
          slug: declaredSlug,
          startLine: i,
          startOffset: offset + line.length + 1,
        };
      }
    } else if (endMatch) {
      if (!open) {
        errors.push(
          `${filePath}: unmatched @end-prompt-region at route "${routeSlug}" line ~${i} (no open region)`,
        );
      } else {
        const endSlug = endMatch[1];
        if (endSlug && endSlug !== open.slug) {
          errors.push(
            `${filePath}: mismatched @end-prompt-region "${endSlug}" does not match open region "${open.slug}" (route "${routeSlug}", line ~${i})`,
          );
        } else {
          const spanStart = open.startOffset;
          const spanEnd = offset;
          const text = routeText.slice(spanStart, spanEnd);
          if (text.trim().length === 0) {
            errors.push(
              `${filePath}: empty @prompt-region "${open.slug}" (route "${routeSlug}", lines ${open.startLine}-${i})`,
            );
          } else {
            spans.push({
              start: routeOffsetInFile + spanStart,
              end: routeOffsetInFile + spanEnd,
              text,
            });
          }
        }
        open = null;
      }
    } else {
      if (LOOSE_BEGIN_RE.test(line)) {
        errors.push(
          `${filePath}: malformed @prompt-region marker at route "${routeSlug}" line ~${i}: "${line.trim()}"`,
        );
      }
      if (LOOSE_END_RE.test(line)) {
        errors.push(
          `${filePath}: malformed @end-prompt-region marker at route "${routeSlug}" line ~${i}: "${line.trim()}"`,
        );
      }
    }
    offset += line.length + 1;
  }

  if (open) {
    errors.push(
      `${filePath}: unmatched @prompt-region "${open.slug}" at route "${routeSlug}" starting line ~${open.startLine} (no @end-prompt-region before end of route section)`,
    );
  }

  return { spans, errors };
}

export interface ScannedEntry {
  key: string;
  kind: EntryKind;
  extraction: ExtractionMode;
  sectionHash: string;
  versions: string[];
}

export interface ScanIssue {
  file: string;
  message: string;
}

export interface ScanResult {
  entries: ScannedEntry[];
  issues: ScanIssue[];
}

/**
 * Scan a single file's already-read source. Exposed separately from
 * scanFiles() so it can be unit tested against synthetic fixtures without
 * touching the filesystem.
 */
export function scanFileContent(filePath: string, source: string): ScanResult {
  const issues: ScanIssue[] = [];
  const entries: ScannedEntry[] = [];
  const boundaries = findRouteBoundaries(source);

  if (boundaries.length === 0) {
    const tokens = findVersionTokens(source);
    if (tokens.length === 0) return { entries, issues };
    entries.push({
      key: filePath,
      kind: "module",
      extraction: "whole-file",
      sectionHash: hashSpans([source]),
      versions: sortedUniqueVersions(tokens),
    });
    return { entries, issues };
  }

  const firstStart = boundaries[0]!.start;
  const moduleText = source.slice(0, firstStart);
  const moduleTokens = findVersionTokens(moduleText);
  if (moduleTokens.length > 0) {
    entries.push({
      key: filePath,
      kind: "module",
      extraction: "module-prefix",
      sectionHash: hashSpans([moduleText]),
      versions: sortedUniqueVersions(moduleTokens),
    });
  }

  const seenKeys = new Set<string>();
  for (let i = 0; i < boundaries.length; i++) {
    const b = boundaries[i]!;
    const sectionStart = b.start;
    const sectionEnd =
      i + 1 < boundaries.length ? boundaries[i + 1]!.start : source.length;
    const routeText = source.slice(sectionStart, sectionEnd);
    const tokens = findVersionTokens(routeText);
    if (tokens.length === 0) continue;

    if (!b.slug) {
      issues.push({
        file: filePath,
        message: `cache-key version token(s) found in a route section whose path could not be parsed (offset ${sectionStart}) — cannot build a stable manifest key for it`,
      });
      continue;
    }

    const key = `${filePath}::${b.slug}`;
    if (seenKeys.has(key)) {
      issues.push({
        file: filePath,
        message: `duplicate route entry key "${key}"`,
      });
      continue;
    }

    const { spans, errors: markerErrors } = extractPromptRegions(
      routeText,
      b.slug,
      sectionStart,
      filePath,
    );
    if (markerErrors.length > 0) {
      for (const m of markerErrors) issues.push({ file: filePath, message: m });
      continue;
    }

    if (spans.length > 0) {
      const outsideVersions = new Set<string>();
      for (const t of tokens) {
        const absIndex = sectionStart + t.index;
        const inside = spans.some(
          (s) => absIndex >= s.start && absIndex < s.end,
        );
        if (!inside) outsideVersions.add(t.version);
      }
      if (outsideVersions.size > 0) {
        issues.push({
          file: filePath,
          message: `route "${b.slug}" declares @prompt-region markers but has version token(s) [${[...outsideVersions].join(", ")}] outside the marked regions — move the cache-key definition inside a @prompt-region block`,
        });
        continue;
      }
      entries.push({
        key,
        kind: "route",
        extraction: "marked",
        sectionHash: hashSpans(spans.map((s) => s.text)),
        versions: sortedUniqueVersions(tokens),
      });
      seenKeys.add(key);
    } else {
      entries.push({
        key,
        kind: "route",
        extraction: "section-fallback",
        sectionHash: hashSpans([routeText]),
        versions: sortedUniqueVersions(tokens),
      });
      seenKeys.add(key);
    }
  }

  return { entries, issues };
}

/**
 * Scan SCAN_ROOT for files containing LLM cache-key version tokens and
 * return one entry per module/route, plus any structural issues found.
 */
export function scanFiles(): ScanResult {
  const files: string[] = [];
  walk(SCAN_ROOT, files);
  files.sort();

  const entries: ScannedEntry[] = [];
  const issues: ScanIssue[] = [];
  for (const full of files) {
    const filePath = toPosix(relative(REPO_ROOT, full));
    const source = readFileSync(full, "utf8");
    const result = scanFileContent(filePath, source);
    entries.push(...result.entries);
    issues.push(...result.issues);
  }
  return { entries, issues };
}

// --- Manifest parsing --------------------------------------------------

/** Legacy (pre-schemaVersion) per-file entry shape. */
export interface LegacyManifestEntry {
  sectionHash: string;
  versions: string[];
  registered: string;
}

export type ParsedManifestKind = "empty" | "v2" | "v1-legacy" | "unknown";

export interface ParsedManifest {
  kind: ParsedManifestKind;
  manifest: Manifest | null;
  legacyEntries: Record<string, LegacyManifestEntry> | null;
  /** Human-readable reason, populated only when kind === "unknown". */
  unknownReason?: string;
}

/**
 * Parse prompt-manifest.json into exactly one of four recognized shapes.
 * This function NEVER silently discards or rewrites data it doesn't
 * recognize — "unknown" is a distinct, terminal outcome that both scripts
 * must refuse to act on automatically.
 */
export function parseManifestFile(raw: string): ParsedManifest {
  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(raw) as Record<string, unknown>;
  } catch (err) {
    return {
      kind: "unknown",
      manifest: null,
      legacyEntries: null,
      unknownReason: `not valid JSON: ${(err as Error).message}`,
    };
  }

  if (!parsed.entries || typeof parsed.entries !== "object") {
    return { kind: "empty", manifest: null, legacyEntries: null };
  }
  const entries = parsed.entries as Record<string, unknown>;

  if (parsed.schemaVersion === SCHEMA_VERSION) {
    for (const [key, value] of Object.entries(entries)) {
      const v = value as Record<string, unknown>;
      if (
        !v ||
        typeof v !== "object" ||
        typeof v.sectionHash !== "string" ||
        !Array.isArray(v.versions) ||
        typeof v.kind !== "string" ||
        typeof v.extraction !== "string" ||
        typeof v.registered !== "string"
      ) {
        return {
          kind: "unknown",
          manifest: null,
          legacyEntries: null,
          unknownReason: `declares schemaVersion ${SCHEMA_VERSION} but entry "${key}" does not match the expected v2 shape`,
        };
      }
    }
    return {
      kind: "v2",
      manifest: parsed as unknown as Manifest,
      legacyEntries: null,
    };
  }

  if (parsed.schemaVersion === undefined) {
    let looksLikeV1 = true;
    for (const value of Object.values(entries)) {
      const v = value as Record<string, unknown>;
      if (
        !v ||
        typeof v !== "object" ||
        typeof v.sectionHash !== "string" ||
        !Array.isArray(v.versions) ||
        typeof v.registered !== "string" ||
        v.kind !== undefined ||
        v.extraction !== undefined
      ) {
        looksLikeV1 = false;
        break;
      }
    }
    if (looksLikeV1) {
      return {
        kind: "v1-legacy",
        manifest: null,
        legacyEntries: entries as Record<string, LegacyManifestEntry>,
      };
    }
    return {
      kind: "unknown",
      manifest: null,
      legacyEntries: null,
      unknownReason:
        "no schemaVersion field, but entries do not match the known legacy (v1) shape",
    };
  }

  return {
    kind: "unknown",
    manifest: null,
    legacyEntries: null,
    unknownReason: `unrecognized schemaVersion ${JSON.stringify(parsed.schemaVersion)} — no migration path is defined for it`,
  };
}
