/**
 * promptManifestLib.ts
 *
 * Shared utilities for the prompt-manifest check and update scripts.
 * No executable top-level code — safe to import from either script.
 *
 * The guard scans every TypeScript file under SCAN_ROOT for LLM cache-key
 * version tokens (e.g. `detail:v1:` or `${modeKey}:v2:`). Each file that
 * contains at least one token gets a single manifest entry recording the
 * file's hash and the sorted list of version tokens detected in it.
 */

import { createHash } from "crypto";
import { readdirSync, readFileSync, statSync } from "fs";
import { resolve, dirname, relative, sep } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export const REPO_ROOT = resolve(__dirname, "../../..");

/**
 * Root directory scanned for files that may contain LLM cache-key version
 * tokens. Anything matching SCAN_FILE_PATTERN below this directory is
 * inspected.
 */
export const SCAN_ROOT = resolve(REPO_ROOT, "artifacts/api-server/src");

/** File-name pattern (matched against the basename) for files to inspect. */
export const SCAN_FILE_PATTERN = /\.ts$/;

/** Directory names skipped during the scan. */
export const SCAN_IGNORED_DIRS = new Set([
  "node_modules",
  "dist",
  "build",
  ".turbo",
]);

export const MANIFEST_FILE = resolve(__dirname, "../../prompt-manifest.json");

export interface ManifestEntry {
  sectionHash: string;
  versions: string[];
  registered: string;
}

export interface Manifest {
  description: string;
  entries: Record<string, ManifestEntry>;
}

export const MANIFEST_DESCRIPTION =
  "Auto-generated by scripts/src/updatePromptManifest.ts — do not edit by hand. " +
  "One entry per file containing LLM cache-key version tokens. " +
  "Existing hashes are immutable: bump a cache-key version in the file before changing its prompt content.";

export function hashText(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

/**
 * A scanned file containing one or more LLM cache-key version tokens.
 * `filePath` is repo-relative and uses forward slashes for portability.
 */
export interface ScannedFile {
  filePath: string;
  sectionHash: string;
  versions: string[];
}

function toPosix(p: string): string {
  return sep === "/" ? p : p.split(sep).join("/");
}

function walk(dir: string, out: string[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const name of entries) {
    if (SCAN_IGNORED_DIRS.has(name)) continue;
    const full = resolve(dir, name);
    let s;
    try {
      s = statSync(full);
    } catch {
      continue;
    }
    if (s.isDirectory()) {
      walk(full, out);
    } else if (s.isFile() && SCAN_FILE_PATTERN.test(name)) {
      out.push(full);
    }
  }
}

/** Extract the sorted list of LLM cache-key version tokens in a file. */
export function extractVersionTokens(source: string): string[] {
  const versions = new Set<string>();
  // Literal prefix form: "detail:v1:", "timeline:v2:", etc.
  for (const m of source.matchAll(/\b[a-z][a-z0-9-]*:(v\d+):/g)) {
    versions.add(m[1]);
  }
  // Dynamic-prefix form: `${modeKey}:v1:`
  for (const m of source.matchAll(/\$\{[^}]+\}:(v\d+):/g)) {
    versions.add(m[1]);
  }
  return [...versions].sort();
}

/**
 * Scan SCAN_ROOT for files containing LLM cache-key version tokens and
 * return one entry per matching file.
 */
export function scanFiles(): ScannedFile[] {
  const files: string[] = [];
  walk(SCAN_ROOT, files);
  files.sort();

  const result: ScannedFile[] = [];
  for (const full of files) {
    const source = readFileSync(full, "utf8");
    const versions = extractVersionTokens(source);
    if (versions.length === 0) continue;
    result.push({
      filePath: toPosix(relative(REPO_ROOT, full)),
      sectionHash: hashText(source),
      versions,
    });
  }
  return result;
}

/**
 * Parse the manifest file. Discards legacy formats (pre-per-file) so the
 * update script can rebuild from scratch.
 */
export function parseManifest(raw: string): Manifest {
  const parsed = JSON.parse(raw) as Record<string, unknown>;
  if (!parsed.entries || typeof parsed.entries !== "object") {
    return { description: MANIFEST_DESCRIPTION, entries: {} };
  }
  const entries = parsed.entries as Record<string, unknown>;
  // Detect legacy per-route entries (no `versions` field) and discard.
  for (const value of Object.values(entries)) {
    if (
      !value ||
      typeof value !== "object" ||
      !Array.isArray((value as { versions?: unknown }).versions)
    ) {
      return { description: MANIFEST_DESCRIPTION, entries: {} };
    }
  }
  return parsed as unknown as Manifest;
}
