import { readdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const TYPES_DIR = join(__dirname, "../../lib/api-zod/src/generated/types");

const EXCLUDED = new Set(["index.ts", "ratePlaceResponse.ts"]);

const files = readdirSync(TYPES_DIR)
  .filter((f) => f.endsWith(".ts") && !EXCLUDED.has(f))
  .sort();

const banner = [
  "/**",
  " * Auto-generated by scripts/src/generateApiZodTypesBarrel.ts",
  " * Run `pnpm run codegen` to regenerate.",
  " * ratePlaceResponse is intentionally excluded: it conflicts with the",
  " * RatePlaceResponse Zod schema already exported from ./generated/api.",
  " */",
].join("\n");

const barrel =
  banner +
  "\n\n" +
  files.map((f) => `export * from "./${f.slice(0, -3)}";`).join("\n") +
  "\n";

writeFileSync(join(TYPES_DIR, "index.ts"), barrel);

console.log(
  `[api-zod barrel] Wrote ${files.length} type exports to generated/types/index.ts`,
);
