// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/style-directions/CoolSlate.tsx": () => import("../components/mockups/style-directions/CoolSlate.tsx"),
  "./components/mockups/style-directions/DarkLuxe.tsx": () => import("../components/mockups/style-directions/DarkLuxe.tsx"),
  "./components/mockups/style-directions/WarmRefined.tsx": () => import("../components/mockups/style-directions/WarmRefined.tsx")
};
