// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/style-directions/CoolSignal.tsx": () => import("../components/mockups/style-directions/CoolSignal.tsx"),
  "./components/mockups/style-directions/CuriousNight.tsx": () => import("../components/mockups/style-directions/CuriousNight.tsx"),
  "./components/mockups/style-directions/FieldNotes.tsx": () => import("../components/mockups/style-directions/FieldNotes.tsx"),
  "./components/mockups/style-directions/SoftDepth.tsx": () => import("../components/mockups/style-directions/SoftDepth.tsx"),
  "./components/mockups/style-directions/UrbanGlow.tsx": () => import("../components/mockups/style-directions/UrbanGlow.tsx"),
  "./components/mockups/style-directions/WarmEmber.tsx": () => import("../components/mockups/style-directions/WarmEmber.tsx")
};
