// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/color-exploration/DeepTeal.tsx": () =>
    import("../components/mockups/color-exploration/DeepTeal.tsx"),
  "./components/mockups/color-exploration/DustyRose.tsx": () =>
    import("../components/mockups/color-exploration/DustyRose.tsx"),
  "./components/mockups/color-exploration/LoadingAnimation.tsx": () =>
    import("../components/mockups/color-exploration/LoadingAnimation.tsx"),
  "./components/mockups/color-exploration/MossOlive.tsx": () =>
    import("../components/mockups/color-exploration/MossOlive.tsx"),
  "./components/mockups/color-exploration/SlateBlue.tsx": () =>
    import("../components/mockups/color-exploration/SlateBlue.tsx"),
  "./components/mockups/entry-screen/EntryScreen.tsx": () =>
    import("../components/mockups/entry-screen/EntryScreen.tsx"),
  "./components/mockups/entry-screen/EntryScreenBrandA.tsx": () =>
    import("../components/mockups/entry-screen/EntryScreenBrandA.tsx"),
  "./components/mockups/entry-screen/EntryScreenBrandB.tsx": () =>
    import("../components/mockups/entry-screen/EntryScreenBrandB.tsx"),
  "./components/mockups/entry-screen/EntryScreenBrandC.tsx": () =>
    import("../components/mockups/entry-screen/EntryScreenBrandC.tsx"),
  "./components/mockups/entry-screen/EntryScreenProposed.tsx": () =>
    import("../components/mockups/entry-screen/EntryScreenProposed.tsx"),
  "./components/mockups/header-redesign/LabeledActions.tsx": () =>
    import("../components/mockups/header-redesign/LabeledActions.tsx"),
  "./components/mockups/header-redesign/SimplifiedBar.tsx": () =>
    import("../components/mockups/header-redesign/SimplifiedBar.tsx"),
  "./components/mockups/header-redesign/WalkFirst.tsx": () =>
    import("../components/mockups/header-redesign/WalkFirst.tsx"),
  "./components/mockups/now-playing/Current.tsx": () =>
    import("../components/mockups/now-playing/Current.tsx"),
  "./components/mockups/now-playing/CurrentLight.tsx": () =>
    import("../components/mockups/now-playing/CurrentLight.tsx"),
  "./components/mockups/now-playing/Proposed.tsx": () =>
    import("../components/mockups/now-playing/Proposed.tsx"),
  "./components/mockups/now-playing/ProposedLight.tsx": () =>
    import("../components/mockups/now-playing/ProposedLight.tsx"),
  "./components/mockups/style-directions/CoolSignal.tsx": () =>
    import("../components/mockups/style-directions/CoolSignal.tsx"),
  "./components/mockups/style-directions/CuriousNight.tsx": () =>
    import("../components/mockups/style-directions/CuriousNight.tsx"),
  "./components/mockups/style-directions/FieldNotes.tsx": () =>
    import("../components/mockups/style-directions/FieldNotes.tsx"),
  "./components/mockups/style-directions/SoftDepth.tsx": () =>
    import("../components/mockups/style-directions/SoftDepth.tsx"),
  "./components/mockups/style-directions/UrbanGlow.tsx": () =>
    import("../components/mockups/style-directions/UrbanGlow.tsx"),
  "./components/mockups/style-directions/WarmEmber.tsx": () =>
    import("../components/mockups/style-directions/WarmEmber.tsx"),
  "./components/mockups/walk-landing/WalkLanding.tsx": () =>
    import("../components/mockups/walk-landing/WalkLanding.tsx"),
};
